title: Berkay Çelebi
description: Siber Güvenlik - CTF WriteUp - Sanal Makine CTF.
show_downloads: true
google_analytics: G-GFWHEDLNKB
google_analytics: G-CMN1Z1RV2Y
remote-theme: jekyll-theme-hacker
#theme: jekyll-theme-hacker
